### ISSUE TITLE
Extend People with tags and searching

### ISSUE THREAD

**Issue by mmnosek** [StarcounterApps/People#103]
We need to track expertise of specific people in Starcounter. The motivation is described here: https://github.com/Starcounter/CompanyTrack/issues/341 Long story short - we want to assign tags and be able to search using this tags on https://inside.starcounter.com

What I would like to see in the People App is:
- Definable list of unique tags (name + color)
- Assigning tag to the person on person page
- List of assigned tags on the person page
- Searching list of the person by tag
- Tag cloud - you click the tag and you get all the persons with tag assigned

I don't want to be too opinionated because it might be developed/implemented in the different ways. Actually, tagging sounds like something not person-specific. It is usually nice to assign the tags to anything and also to be able to search for everything you have in the system.

I see three options to fulfill requirements:
1. Implement it inside People (simplest, but not very Starcounter-ish :))
2. Create Tag app (but then we have one more App to maintain and searching is probably limited to the tags only)
3. Include it into SearchApp, Add Tags to `Simplified` (Tags are about searching, aren't they?). No additional apps to maintain, searching in one place + we can tag all `Something` and `Somebody`.

Personally, I vote for option 3. It should be reasonably easy to map and blend!

cc @warpech @habib535 @stefanedqvist

**Comment by mmnosek** [comment]
It may also fit the CRM we build, right?

**Comment by warpech** [comment]
@bouguila can you pls put this to the roadmap, instead of `Add roles/skillsets relations to a Person` as discussed on https://github.com/Starcounter/Minutes/issues/62?

**Comment by bouguila** [comment]
@warpech yes sure!

**Comment by bouguila** [comment]
closing as done in c543cc3

**Comment by mmnosek** [comment]
@bouguila wait, it's not merged and I didn't see the result ;)

**Comment by bouguila** [comment]
@mmnosek can we close this issue now since c543cc3 is merged into develop?

**Comment by mmnosek** [comment]
Thanks @bouguila, closing!
