### ISSUE TITLE
Add info about being unauthenticated user

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/People#105]
Right now, when you start People app and access it without being signed in, you see an empty response.

![2017-07-11 17_33_18-localhost_8080_people](https://user-images.githubusercontent.com/566463/28076739-e09ac542-665f-11e7-86ce-0627418be592.png)

Compare this to what you get in such case in UserAdmin:

![2017-07-11 17_33_32-useradmin](https://user-images.githubusercontent.com/566463/28076477-2843cd7c-665f-11e7-9ab6-7322cb902bca.png)

Moreover, when you start Sign In app, you actually get a Sign In form blended to the response from UserAdmin:

![2017-07-11 17_35_39-useradmin](https://user-images.githubusercontent.com/566463/28076551-614c8834-665f-11e7-8d57-8c54518271d5.png)

The solution in UserAdmin is not the best in the world either (it does not have the correct status code), but is much better than what is in People app. When we are happy with a good solution, we should copy it to other apps.

**Comment by bouguila** [comment]
closing as fixed in 380594f
