### ISSUE TITLE
Refactor how the deletion of items work

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/People#116]
In the people app, when we delete something, for example a user, we use `testUser.Delete();`
Instead, this needs to be changed to `testUser.IsDeleted = true;`

After changing how everything is deleted, we should also change what users are being displayed in different lists.

For example, when displaying all the users, we should exclude all the users that have their `IsDeleted` toggled. So we should only display users that "is not deleted".

Same thing should be applied to organizations

**Comment by Joltrix** [comment]
cc @warpech @bouguila 

What about addresses or phonenumbers by the way? Should we toggle them deleted as well, or just delete them?

- if we aim to be able to add an undo button eventually, perhaps we should just change how all the deletions work?

**Comment by warpech** [comment]
The way I understand it: when you delete a person, nothing changes about the phone numbers. 

You have an undeleted phone number of a deleted person.

**Comment by warpech** [comment]
Maybe the property should be called `Deleted`, not `IsDeleted`. In Simplified we have a little bit of both conventions, but `Deleted` is more common. 

See: https://github.com/StarcounterApps/Simplified/pull/66

**Comment by Joltrix** [comment]
Yeah, but what if we only delete a phone number? Should that also be toggled? or should that actually disappear? At the moment, I've made it so that nothing gets deleted, I only flip their `IsDeleted` flag. But ofc, we can change this.

In the PR you linked, do you mean the Disabled flag?

We can change the naming to Deleted if you want :)

**Comment by warpech** [comment]
> At the moment, I've made it so that nothing gets deleted, I only flip their IsDeleted flag.

I think that's correct.

> In the PR you linked, do you mean the Disabled flag?

Yes, so I think that the name for this method should be `Deleted`. If you agree.

**Comment by Joltrix** [comment]
This has been implemented, and will be pushed to the develop branch once [this PR](https://github.com/StarcounterApps/People/pull/117) has been merged

**Comment by Joltrix** [comment]
Since the above mentioned PR has been merged, I'll go ahead and close this issue
