### ISSUE TITLE
Bad code in UnauthorizedPage.html

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/People#118]
`UnauthorizedPage.html`, which was added in https://github.com/StarcounterApps/People/pull/106 uses inline styles. It should use CSS BEM classes.

Also, there is an incorrect tag `</">` and empty `<style>` element.

`template is="dom-bind"` is not needed in this file because no variables are used.

https://github.com/StarcounterApps/People/blob/1d57bc7f7aec70000fab8b05553345ef8d7c5405/src/People/wwwroot/People/viewmodels/UnauthorizedPage.html

cc @bouguila, @habib535

**Comment by bouguila** [comment]
you're right! i will fix that
