### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/People#124]
### Steps to reproduce
Open the following link, and SignIn using default credentials
https://bi.adfenix.com/people

### Technical information
I am sure this is due to some Dirty Data. Cuz this doesn't happen if my DB is clean

##### Starcounter version 
2.3.1.7166
##### Involved apps' version
ODataApi
People
Signin
UserAdmin
WebSite

### Screenshot
![image](https://user-images.githubusercontent.com/4388707/30370112-dfdf9bfc-9876-11e7-95c8-e0c8e8c94b95.png)

**Comment by miyconst** [comment]
https://github.com/StarcounterApps/Simplified/blob/a95fa3776d5db41cc532dbae79cb796544ae8ade/Ring2/OrganizationMember.cs#L17

Somehow there are `Simplified.Ring2.OrganizationMember` items where the `Member` property is `null`.

**Comment by rogeralsing** [comment]
FYI: I've got the same issue here when trying out the people app
