### ISSUE TITLE
confirm dialog is not showing when delete is clicked

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/People#125]
### Steps to reproduce

1. Build and run people and signIn or just go to http://inside.starcounter.com/people/persons
2. Login using your credentials
3. go to `/people/persons`
4. click `Delete` button on any person row 

### Expected result
a confirm dialog should popup asking for confirmation
### Actual result
nothing appears

##### Involved apps' version

 - StarcounterApps/People@6.0.3 or actual develop branch
 - StarcounterApps/SignIn@6.0.0 or actual master branch
 
##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

**Comment by warpech** [comment]
From what I have tested with the app versions provided in https://github.com/Palindrom/Palindrom/issues/156, this affects:

- deleting a person
- deleting an organisation
- deleting a custom field
- maybe deleting other data as well?

**Comment by bouguila** [comment]
@warpech basically any delete action that invokes the confirm dialog

**Comment by bouguila** [comment]
closing as fixed in  [b10885d](https://github.com/StarcounterApps/People/commit/b10885d4646e9313a1fcdf1390ae4959ba352286)
