### ISSUE TITLE
Redirect to main page after saving changes in persons profile is unnecessary

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/People#128]
When You change something in person page and click save button You will be redirected to `http://inside.starcounter.com/people/persons` page. It's completely unnecessary and mostly annoying. I suggest that after saving changes, person page should be refreshed or nothing at all should happen (As far as I saw this solution is mostly used in our apps).

**Comment by bouguila** [comment]
i agree with @PatrykSzwer on the point that it is pointless to redirect the user the `/persons` or to `/organizations` on `Save` button click accordingly from a person page and an organization page as the user may want to continue editing even after hitting Save.
@warpech what do you think?

**Comment by PatrykSzwer** [comment]
Closing as done.
