### ISSUE TITLE
Country dropdownlist in people page is bugged

### ISSUE THREAD

**Issue by rogeralsing** [StarcounterApps/People#130]
### Steps to reproduce
Open up any person for edit, start typing Sweden.

### Expected result
The dropdown stays close to the inputbox

### Actual result
The dropdown floats freely at random y-positions

![image](https://user-images.githubusercontent.com/647031/30774088-978f75ac-a07d-11e7-8bba-a8df2ccc3e28.png)

**Comment by bouguila** [comment]
@rogeralsing are you producing this issue locally or on http://inside.starcounter.com? 
if testing locally could you please specify what People app version are you running? 
also what web browser are you using, as everything looks fine in Chrome?

**Comment by bouguila** [comment]
update: i was able to reproduce it on Firefox. The issue should be solved with #133

**Comment by bouguila** [comment]
closing as fixed in [#ffbae15](https://github.com/StarcounterApps/People/commit/ffbae154df093648d0787e385750cd1b20d87734)
