### ISSUE TITLE
Question : Is it possible to have Picture on persons page?

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/People#131]
We have some users with pictures, but in this page, we can not easily tell which user has the picture. Is there an easy way to add the picture here?

![image](https://user-images.githubusercontent.com/4388707/30775765-8790a064-a09a-11e7-931a-46dfec86a639.png)

**Comment by bouguila** [comment]
if you run InsideStarcounterMapper you will be able to see small picture thumbnails next to a person's row

![miniature](https://user-images.githubusercontent.com/12608524/30809405-eb776294-a201-11e7-8327-239a3dfd8cd5.PNG)

**Comment by bouguila** [comment]
I think that this feature should be available on People app with no external dependencies (with the only requirement Images app running, of course)
@warpech WDYT?

**Comment by atifwaqar** [comment]
> if you run InsideStarcounterMapper you will be able to see small picture thumbnails next to a person's row

@bouguila Thanks, This worked for me.

**Comment by bouguila** [comment]
closing as answered.
