### ISSUE TITLE
Add filtering functionality to the people app

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/People#144]
In the page where all the people are being listed (PersonsPage), all of the people are listed alphabetically, and the only navigation option the user has is the pagination. In cases where the people app only has around 10-50 persons, it's a rather smooth way of navigating. If the people app however have over 1000 people, it becomes a lot more difficult to find someone.

For example, if a program has 3000 persons, there will be 100 pagination pages,
The pagination will display the current page (for example, 5), and the 2 pages before, and the two pages after. So 5 pages, + First/Previous + Next/Last

So, how does one find a person that is on page 60? (for example), The user would have to start at the last page, and jump 40 pages "to the left". Which is quite unintuitive.

Perhaps we can add an additional layer of "filtering", perhaps filter the users by the first letter in their name first, and then applying the pagination to the people who starts with X

The problem then however becomes, what about letters from other alphabets, like the Swedish Å Ä Ö, or any Greek letter for example.

One solution would be to use the Search app, but perhaps we want a standalone solution, as to not make the people app reliant on the Search app
Does anyone have a good idea as to how we can achieve this?

cc @warpech @bouguila @habib535 @Mihaiii @LarsTjernstrom @andwah

**Comment by Mihaiii** [comment]
I don't think we **want** a standalone solution for this.
Search app solves this problem, like you said, and this is what we want afaik: to use multiple apps.

My 2 cents.
