### ISSUE TITLE
Implement the new design

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/People#92]
Implement the new design presented in https://github.com/Starcounter/RebelsLounge/issues/121

The work has already started in branch: https://github.com/StarcounterApps/People/tree/feature/implement-new-ui

@threezool what is the current state of it? Please meet with @andwah, @bouguila to discuss the next steps.

**Comment by threezool** [comment]
The design has evolved from the work i had started so i don't think its worth keeping that and just start fresh with the new design changes in mind.

**Comment by andwah** [comment]
i have not yet had any feedback from @Starcounter-Jack  about the latest design...

**Comment by bouguila** [comment]
closing as done in 380594f
