### ISSUE TITLE
Setting new password does not work in 2 locations

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/People#93]
### Steps to reproduce
1. Run following apps:
 a. Launcher
 b. UserAdmin
 c. SignIn
 d. People
2. Create a user
3. go to `http://localhost:8080/people/persons/{?}` or `http://localhost:8080/useradmin/admin/users/{?}`
4. Click on `SET NEW PASSWORD` button
5. Set new password
6. click save (and as soon as I click, I get an exception on the page)

### Expected result
7. Logging in using new password should work, but new password is not set, I still have to use the old password to log in.

##### Starcounter version 
Starcounter-RC-2.3.0.5916

##### Involved apps' version
Launcher
UserAdmin
SignIn
People
 
### Screenshot
![image](https://user-images.githubusercontent.com/4388707/27077911-fc8c62f4-5031-11e7-951e-5e419f1046cf.png)

**Comment by miyconst** [comment]
@bouguila this issue might be inside of a different app, because this page is rendered by People app which includes a view from UserAdmin app, which includes a view from SignIn app :).

**Comment by warpech** [comment]
@atifwaqar could you please paste the error message from the log in Adminstrator?

**Comment by bouguila** [comment]
@atifwaqar could you please specify which app versions you use for this issue?

**Comment by bouguila** [comment]
This issue is related to [UserAdmin](https://github.com/StarcounterApps/UserAdmin) app, Save button is actually hardcoded to redirect the page to `"/UserAdmin/admin/users"` besides committing the transaction, which is anti-pattern regarding this Starcounter/Guidelines#27.
cc @warpech

**Comment by warpech** [comment]
Such a great finding! Thank you @bouguila for connecting-the-dots. Let's discuss the solution in https://github.com/Starcounter/Guidelines/issues/27

**Comment by bouguila** [comment]
Closing as related to other UserAdmin.
