### ISSUE TITLE
Clicking on Add Person give an exception

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/People#94]
The setup (SC verions & apps) are same as https://github.com/StarcounterApps/People/issues/93

### Steps to reproduce
1. Go to http://localhost:8080/people/persons
2. press button `ADD PERSON`, and you will see the exception
lets move forward, and refresh the page (on clicking the button the page url is changed to http://localhost:8080/people/persons/add)
3. Add firstName, lastName and then click on `SAVE` button, and you will see 2nd exception (the user is added at this stage though)
4. Next, go to the user's page (http://localhost:8080/people/persons/{?})
5. Clicking on any of the 4 buttons also gives the exception (sometimes, not always) `ADD ADDRESS`, `ADD EMAIL ADDRESS`, `ADD PHONE ADDRESS`, `ADD CUSTOM FIELD`. (My guess is that if the user object is not created for this person, these exceptions occur, But again, its an assumption.)

### Screenshot
![image](https://user-images.githubusercontent.com/4388707/27080919-5e1e282a-503e-11e7-9234-210144328d75.png)

**Comment by warpech** [comment]
@atifwaqar could you please paste the error message from the log in Adminstrator?

**Comment by bouguila** [comment]
@atifwaqar can you still reproduce the issue? do you have any further information about the error?

**Comment by bouguila** [comment]
Closing as can't to reproduce.

**Comment by atifwaqar** [comment]
@bouguila Sorry I missed your last comment. 
And i'm not able to reproduce this one now.  Thanks for the fix whoever did it :)
