### ISSUE TITLE
Editing person with Images app creates new empty Person which causes exception.

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/People#95]
### Steps to reproduce
1. Run SignIn, People and Images app.
2. Go to edit view of any person in People app.
3. Change anything(optional) and click save button.
### Expected result
Person has changed edited fields (if changed in step 3), or nothing happen.

### Actual result
Person is changed but also there is new, empty person created. That causes exception in People app.

### Screenshot

![image](https://user-images.githubusercontent.com/25042256/27177313-344635c2-51c6-11e7-8465-4da782760612.png)

After commenting line with exception:

![capture](https://user-images.githubusercontent.com/25042256/27177410-940b2e36-51c6-11e7-91f3-abc3f2dd4617.PNG)

Regardless the empty person issue that actually shows lack in verification of People app. Persons can be edited from other app and that issue will came again. I suggest to add verification to AddParentsToOrganizations method to avoid exceptions in future. Something like this could do the trick:

```
var organisations = OrganizationMember.OrganizationsOfAMember(this.Data);
if (organisations.First != null)
{
      this.ParentNameList.Data = organisations.OrderBy(x => x.Name);
}

**Comment by bouguila** [comment]
closing as fixed in StarcounterApps/Images#103
