### ISSUE TITLE
People app crashes(/misbehaves) on adding an image to a person

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/People#97]
### Steps to reproduce
1. Install and run the app suite on a fresh DB
2. Generate admin user
3. view admin user in person app
4. drag and image in image box
5. press save button

##### Starcounter version 
Starcounter-RC-2.3.1.6600

##### Involved apps' version
People `master`
Images `Develop`
Launcher `Develop`
Signin `Develop`
UserAdmin `Develop`
Website `Develop`

**Comment by bouguila** [comment]
closing as fixed in StarcounterApps/Images#103
